package com.itany.nmms.entity;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.staff_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.staff_name
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.login_name
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.password
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.phone
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.email
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.dept_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.role
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.is_valid
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.create_date
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.create_staff_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    private Integer createStaffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.staff_id
     *
     * @return the value of sys_staff.staff_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.staff_id
     *
     * @param staffId the value for sys_staff.staff_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.staff_name
     *
     * @return the value of sys_staff.staff_name
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.staff_name
     *
     * @param staffName the value for sys_staff.staff_name
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.login_name
     *
     * @return the value of sys_staff.login_name
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.login_name
     *
     * @param loginName the value for sys_staff.login_name
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.password
     *
     * @return the value of sys_staff.password
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.password
     *
     * @param password the value for sys_staff.password
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.phone
     *
     * @return the value of sys_staff.phone
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.phone
     *
     * @param phone the value for sys_staff.phone
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.email
     *
     * @return the value of sys_staff.email
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.email
     *
     * @param email the value for sys_staff.email
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.dept_id
     *
     * @return the value of sys_staff.dept_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.dept_id
     *
     * @param deptId the value for sys_staff.dept_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.role
     *
     * @return the value of sys_staff.role
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.role
     *
     * @param role the value for sys_staff.role
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.is_valid
     *
     * @return the value of sys_staff.is_valid
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.is_valid
     *
     * @param isValid the value for sys_staff.is_valid
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.create_date
     *
     * @return the value of sys_staff.create_date
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.create_date
     *
     * @param createDate the value for sys_staff.create_date
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.create_staff_id
     *
     * @return the value of sys_staff.create_staff_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public Integer getCreateStaffId() {
        return createStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.create_staff_id
     *
     * @param createStaffId the value for sys_staff.create_staff_id
     *
     * @mbggenerated Fri Nov 23 11:46:15 CST 2018
     */
    public void setCreateStaffId(Integer createStaffId) {
        this.createStaffId = createStaffId;
    }
}